# Generated by Django 3.2.9 on 2022-05-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=30)),
                ('definition', models.TextField()),
                ('hint', models.TextField()),
                ('zipf_freq', models.FloatField()),
            ],
            options={
                'db_table': 'words_3',
                'managed': False,
            },
        ),
    ]
