# Generated by Django 3.2.9 on 2023-02-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crossword_generator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Words3',
        ),
    ]
